/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One resolved external API call expression in customer code. SPEC §5.1/§6.1/§8. Deliberately excludes owning-service/team and critical-path flag (need CODEOWNERS integration, not week 1) and any code snippet (SPEC §10 — no code retention beyond file path and line numbers).
 */
export interface CallSite {
  surface: SurfaceID;
  /**
   * Repository identifier, e.g. "owner/name".
   */
  repo: string;
  /**
   * Commit the extraction ran against. Null when indexing a working tree with uncommitted changes.
   */
  commit_sha?: string | null;
  /**
   * Path relative to the repository root.
   */
  file_path: string;
  line_start: number;
  line_end: number;
  language: "python" | "typescript";
  /**
   * Provider API version pinned at or around this call site (SPEC §6.1). Null when unpinned — most call sites, per spec.
   */
  api_version?: string | null;
  /**
   * SPEC §6.1 resolution state. literal: statically resolved value. dynamic: argument present but assembled from config/env/variable. absent: not supplied; provider default applies.
   */
  value_binding: "literal" | "dynamic" | "absent";
  /**
   * Per-call-site confidence (SPEC §8.3). 1.0 for statically resolved typed SDK calls; lower for heuristic matches.
   */
  confidence: number;
  /**
   * Which funnel stage resolved this call site, e.g. "tree_sitter.python", "tree_sitter.typescript". SPEC §8.1 — week 1 covers steps 1-2 only; no "embeddings"/"small_model"/"frontier_model" values yet.
   */
  extractor: string;
  /**
   * sha256 of the file's bytes at extraction time. SPEC §8.2 incremental re-indexing key.
   */
  file_content_hash: string;
}
/**
 * The canonical identity this call site resolves to.
 */
export interface SurfaceID {
  /**
   * Lowercase dotted path, e.g. "openai", "anthropic". Controlled vocabulary — see shared/vocabulary/providers.json.
   */
  provider: string;
  /**
   * Lowercase dotted path, e.g. "chat.completions", "messages". Controlled vocabulary.
   */
  resource: string;
  /**
   * e.g. "create". Controlled vocabulary. Null means every operation on the resource.
   */
  operation?: string | null;
  /**
   * e.g. "model", "metadata.customer_id". Null means the surface itself, not one of its fields.
   */
  field_path?: string | null;
  /**
   * e.g. "gpt-4-0613". Stored verbatim as the provider writes it — an opaque token the provider owns, never canonicalised. Null means every value of the field (or, if field_path is also null, the surface itself).
   */
  value?: string | null;
}
