/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A normalized provider change, emitted by a detection source and resolved to a canonical surface identity.
 */
export interface ChangeEvent {
  surface: SurfaceID;
  replacement_surface?: SurfaceID | null;
  change_type:
    | "surface_added"
    | "surface_removed"
    | "type_changed"
    | "requiredness_changed"
    | "model_deprecated"
    | "model_retired";
  severity: "info" | "warning" | "breaking";
  source: "sdk_diff" | "model_registry";
  confidence: number;
  summary?: string | null;
  announced_at?: string | null;
  effective_at?: string | null;
  applies_from?: string | null;
  applies_to?: string | null;
  detected_at: string;
  provenance: {
    source_url: string;
    package_ecosystem?: "pypi" | "npm" | null;
    package_name?: string | null;
    from_version?: string | null;
    to_version?: string | null;
  };
}
/**
 * Canonical identity for an external API surface. SPEC §6.1 — the single hardest thing to change later; every stored call site and historical change event references it. provider/resource/operation are drawn from shared/vocabulary/providers.json, enforced by the generated model's validators, not by this schema alone (JSON Schema cannot express the provider→resource→operation dependency).
 */
export interface SurfaceID {
  /**
   * Lowercase dotted path, e.g. "openai", "anthropic". Controlled vocabulary — see shared/vocabulary/providers.json.
   */
  provider: string;
  /**
   * Lowercase dotted path, e.g. "chat.completions", "messages". Controlled vocabulary.
   */
  resource: string;
  /**
   * e.g. "create". Controlled vocabulary. Null means every operation on the resource.
   */
  operation?: string | null;
  /**
   * e.g. "model", "metadata.customer_id". Null means the surface itself, not one of its fields.
   */
  field_path?: string | null;
  /**
   * e.g. "gpt-4-0613". Stored verbatim as the provider writes it — an opaque token the provider owns, never canonicalised. Null means every value of the field (or, if field_path is also null, the surface itself).
   */
  value?: string | null;
}
