/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Layer 1 inventory (SPEC §5.1) as produced by `avert inventory` from Postgres. Lifecycle status comes from the impact join (join.py) against persisted change events, never recomputed by a consumer.
 */
export interface Inventory {
  generated_at: string;
  repositories: string[];
  providers: string[];
  call_site_count: number;
  /**
   * Call sites whose status is retiring or retired.
   */
  attention_count: number;
  dependencies: Dependency[];
}
export interface Dependency {
  surface: SurfaceID;
  value_binding: "literal" | "dynamic" | "absent";
  /**
   * current: no matching change event. retiring: definite match, effective date in the future. retired: definite match, effective date passed. unknown: value not statically resolved (possible match only).
   */
  status: "current" | "retiring" | "retired" | "unknown";
  effective_at: string | null;
  /**
   * Replacement value from the earliest matching change event.
   */
  replacement: string | null;
  /**
   * @minItems 1
   */
  locations: [Location, ...Location[]];
}
/**
 * Canonical identity for an external API surface. SPEC §6.1 — the single hardest thing to change later; every stored call site and historical change event references it. provider/resource/operation are drawn from shared/vocabulary/providers.json, enforced by the generated model's validators, not by this schema alone (JSON Schema cannot express the provider→resource→operation dependency).
 */
export interface SurfaceID {
  /**
   * Lowercase dotted path, e.g. "openai", "anthropic". Controlled vocabulary — see shared/vocabulary/providers.json.
   */
  provider: string;
  /**
   * Lowercase dotted path, e.g. "chat.completions", "messages". Controlled vocabulary.
   */
  resource: string;
  /**
   * e.g. "create". Controlled vocabulary. Null means every operation on the resource.
   */
  operation?: string | null;
  /**
   * e.g. "model", "metadata.customer_id". Null means the surface itself, not one of its fields.
   */
  field_path?: string | null;
  /**
   * e.g. "gpt-4-0613". Stored verbatim as the provider writes it — an opaque token the provider owns, never canonicalised. Null means every value of the field (or, if field_path is also null, the surface itself).
   */
  value?: string | null;
}
export interface Location {
  repo: string;
  file_path: string;
  line: number;
  confidence: number;
}
