# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit.

# generated by datamodel-codegen:
#   filename:  call_site.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from . import surface_id_schema


class CallSite(BaseModel):
    """
    One resolved external API call expression in customer code. SPEC §5.1/§6.1/§8. Deliberately excludes owning-service/team and critical-path flag (need CODEOWNERS integration, not week 1) and any code snippet (SPEC §10 — no code retention beyond file path and line numbers).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    surface: surface_id_schema.SurfaceID = Field(
        ..., description='The canonical identity this call site resolves to.'
    )
    repo: str = Field(..., description='Repository identifier, e.g. "owner/name".')
    commit_sha: str | None = Field(
        None,
        description='Commit the extraction ran against. Null when indexing a working tree with uncommitted changes.',
    )
    file_path: str = Field(..., description='Path relative to the repository root.')
    line_start: conint(ge=1)
    line_end: conint(ge=1)
    language: Literal['python', 'typescript']
    api_version: str | None = Field(
        None,
        description='Provider API version pinned at or around this call site (SPEC §6.1). Null when unpinned — most call sites, per spec.',
    )
    value_binding: Literal['literal', 'dynamic', 'absent'] = Field(
        ...,
        description='SPEC §6.1 resolution state. literal: statically resolved value. dynamic: argument present but assembled from config/env/variable. absent: not supplied; provider default applies.',
    )
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='Per-call-site confidence (SPEC §8.3). 1.0 for statically resolved typed SDK calls; lower for heuristic matches.',
    )
    extractor: str = Field(
        ...,
        description='Which funnel stage resolved this call site, e.g. "tree_sitter.python", "tree_sitter.typescript". SPEC §8.1 — week 1 covers steps 1-2 only; no "embeddings"/"small_model"/"frontier_model" values yet.',
    )
    file_content_hash: constr(pattern=r'^[a-f0-9]{64}$') = Field(
        ...,
        description="sha256 of the file's bytes at extraction time. SPEC §8.2 incremental re-indexing key.",
    )
