# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit.

# generated by datamodel-codegen:
#   filename:  change_event.schema.json

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, confloat

from . import surface_id_schema


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_url: AnyUrl
    package_ecosystem: Literal['pypi', 'npm'] | None = None
    package_name: str | None = None
    from_version: str | None = None
    to_version: str | None = None


class ChangeEvent(BaseModel):
    """
    A normalized provider change, emitted by a detection source and resolved to a canonical surface identity.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    surface: surface_id_schema.SurfaceID
    replacement_surface: surface_id_schema.SurfaceID | None = None
    change_type: Literal[
        'surface_added',
        'surface_removed',
        'type_changed',
        'requiredness_changed',
        'model_deprecated',
        'model_retired',
    ]
    severity: Literal['info', 'warning', 'breaking']
    source: Literal['sdk_diff', 'model_registry']
    confidence: confloat(ge=0.0, le=1.0)
    summary: str | None = None
    announced_at: date | None = None
    effective_at: date | None = None
    applies_from: str | None = None
    applies_to: str | None = None
    detected_at: AwareDatetime
    provenance: Provenance
