# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit.

# generated by datamodel-codegen:
#   filename:  impact.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, conint

from . import change_event_schema


class Match(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    repo: str
    file_path: str
    line_start: conint(ge=1)
    line_end: conint(ge=1)
    match_kind: Literal['definite', 'possible'] = Field(
        ...,
        description='join.py: definite for a literal value match or a value-less event; possible for a dynamically bound value.',
    )
    confidence: confloat(ge=0.0, le=1.0)


class Impact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event: change_event_schema.ChangeEvent
    blast_radius: str = Field(
        ...,
        description='Plain-language statement, e.g. "3 call sites in 2 files across 1 repository (1 possible)".',
    )
    matches: list[Match]


class ImpactReport(BaseModel):
    """
    Layer 2 change feed (SPEC §5.2): every persisted change event joined to the call sites it affects, as produced by `avert impacts`. Events with no affected call sites are included with an empty match list so a consumer can distinguish 'nothing tracked' from 'not affected'.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    generated_at: AwareDatetime
    impacts: list[Impact]
