# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit.

# generated by datamodel-codegen:
#   filename:  inventory.schema.json

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, conint

from . import surface_id_schema


class Location(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    repo: str
    file_path: str
    line: conint(ge=1)
    confidence: confloat(ge=0.0, le=1.0)


class Dependency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    surface: surface_id_schema.SurfaceID
    value_binding: Literal['literal', 'dynamic', 'absent']
    status: Literal['current', 'retiring', 'retired', 'unknown'] = Field(
        ...,
        description='current: no matching change event. retiring: definite match, effective date in the future. retired: definite match, effective date passed. unknown: value not statically resolved (possible match only).',
    )
    effective_at: date | None
    replacement: str | None = Field(
        ..., description='Replacement value from the earliest matching change event.'
    )
    locations: list[Location] = Field(..., min_length=1)


class Inventory(BaseModel):
    """
    Layer 1 inventory (SPEC §5.1) as produced by `avert inventory` from Postgres. Lifecycle status comes from the impact join (join.py) against persisted change events, never recomputed by a consumer.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    generated_at: AwareDatetime
    repositories: list[str]
    providers: list[str]
    call_site_count: conint(ge=0)
    attention_count: conint(ge=0) = Field(
        ..., description='Call sites whose status is retiring or retired.'
    )
    dependencies: list[Dependency]
