# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit.

# generated by datamodel-codegen:
#   filename:  surface_id.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, constr


class SurfaceID(BaseModel):
    """
    Canonical identity for an external API surface. SPEC §6.1 — the single hardest thing to change later; every stored call site and historical change event references it. provider/resource/operation are drawn from shared/vocabulary/providers.json, enforced by the generated model's validators, not by this schema alone (JSON Schema cannot express the provider→resource→operation dependency).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    provider: constr(pattern=r'^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$') = Field(
        ...,
        description='Lowercase dotted path, e.g. "openai", "anthropic". Controlled vocabulary — see shared/vocabulary/providers.json.',
    )
    resource: constr(pattern=r'^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$') = Field(
        ...,
        description='Lowercase dotted path, e.g. "chat.completions", "messages". Controlled vocabulary.',
    )
    operation: constr(pattern=r'^[a-z][a-z0-9_]*$') | None = Field(
        None,
        description='e.g. "create". Controlled vocabulary. Null means every operation on the resource.',
    )
    field_path: str | None = Field(
        None,
        description='e.g. "model", "metadata.customer_id". Null means the surface itself, not one of its fields.',
    )
    value: str | None = Field(
        None,
        description='e.g. "gpt-4-0613". Stored verbatim as the provider writes it — an opaque token the provider owns, never canonicalised. Null means every value of the field (or, if field_path is also null, the surface itself).',
    )
