#!/usr/bin/env bash
# Generates typed models from shared/schemas/*.json.
# Generated output is committed; CI fails if regeneration produces a diff
# (STRUCTURE.md §2) — consumers never run this script themselves.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Python target: engine/avert/models/ ---
cd "$REPO_ROOT/engine"
uv run datamodel-codegen \
  --input "$SCRIPT_DIR/schemas" \
  --input-file-type jsonschema \
  --output avert/models \
  --output-model-type pydantic_v2.BaseModel \
  --enum-field-as-literal all \
  --use-schema-description \
  --disable-timestamp \
  --collapse-root-models

# Stamp a do-not-edit header on every generated file.
for f in avert/models/*.py; do
  [ -f "$f" ] || continue
  if ! head -1 "$f" | grep -q "GENERATED"; then
    { echo "# GENERATED by shared/generate.sh from shared/schemas/ — do not hand-edit."; echo; cat "$f"; } > "$f.tmp"
    mv "$f.tmp" "$f"
  fi
done

# --- TypeScript target: app/src/types/ ---
cd "$REPO_ROOT/app"
cd "$SCRIPT_DIR/schemas"
for schema in *.schema.json; do
  "$REPO_ROOT/app/node_modules/.bin/json2ts" \
    --input "$schema" \
    --output "$REPO_ROOT/app/src/types/${schema%.schema.json}.ts"
done

echo "Generated: engine/avert/models/ app/src/types/"
